name: 'Run Tests with BrowserStack'

on: [push]

concurrency:
  group: run-tests-with-browserstack
  cancel-in-progress: true

env:
  BROWSERSTACK_BUILD_IDENTIFIER: ${{ github.sha }}

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'BrowserStack Env Setup'
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
       
      - name: 'BrowserStack Local Tunnel Setup'
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: start
          local-identifier: random

      - name: 'Install Percy'
        run: |
             npm install @percy/cli
             npm install browserstack-node-sdk

      - name: 'Install Python dependencies'
        run: |
             python3 -m venv env
             source env/bin/activate && pip3 install -r requirements.txt

      - name: 'Running test on BrowserStack'
        run: |
             source env/bin/activate && npx percy exec --verbose -- browserstack-sdk pytest tests/test_admin.py
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}

      - name: 'BrowserStackLocal Stop'
        uses: browserstack/github-actions/setup-local@master
        with:
          local-testing: stop
