name: 'Run Tests with Percy'

on: [push]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout the repository'
        uses: actions/checkout@v2

      - name: 'BrowserStack Env Setup'
        uses: browserstack/github-actions/setup-env@master
        with:
          username: ${{ secrets.BSTACK_NAME_ }}
          access-key: ${{ secrets.BSTACK_ACC_ }}
      - name: 'Install Percy'
        run: |
             npm install @percy/cli
             npm install browserstack-node-sdk

       
     

      - name: 'Building web application to be tested'
        run:  pip3 install -r requirements.txt

    

      - name: 'Running test on BrowserStack'
        run: npx percy exec -- browserstack-sdk pytest tests/test_courses.py
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN_}}

      
